version: '3'

services:
  logs-service:
    build: 
      context: ./../logs-service
      dockerfile: dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1