## Build and start docker compose
up: 
	@echo "Building and starting docker compose"
	docker-compose up -d --build
	@echo "Docker compose started"

## Stop and remove docker compose
down: 
	@echo "Stopping and removing docker compose"
	docker-compose down
	@echo "Docker compose stopped"