# dockerfile for calculator using nodejs
# typescript files must be build and packaged 

FROM node:18-alpine

# Create app directory
WORKDIR /app

COPY . /app

RUN npm install

RUN npm install -g typescript

RUN tsc

COPY ./dist /app


EXPOSE 3000
CMD [ "node", "index.js" ]

# docker build -t calculator .
# docker run -p 3000:3000 calculator